services:
  php:
    container_name: laravel-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  web:
    container_name: nginx-web
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - postgres

  postgres:
    container_name: postgres
    image: postgres:17.6-bookworm
    environment:
      POSTGRES_DB: laravel-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd4laravel
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "pg_stat_statements.track=all"
    ports:
      - "5432:5432"
    restart: no
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
#    networks:
#      - postgres_net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: pgadminpwd4laravel
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: no
    depends_on:
      - postgres
#    networks:
#      - postgres_net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  pgadmin-data:
#
#networks:
#  postgres_net:
#    driver: bridge
